---
- hosts: datacenter
  connection: network_cli
  gather_facts: no
  collections:
     - dellemc.enterprise_sonic
  vars:
    "host_name": "test-name"
  tasks:
  #  - name: "Configure description for interface in native name"
  #    sonic_config:
  #      commands:
  #        - description Ethernet0
  #      parents:
  #        - interface Ethernet0

   # Same prompt and answer for cli "no interface-naming standard" 
   - name: "Configure cli with prompts on SONiC device"
     sonic_config:
       commands:
         - command: "hostname {{host_name}}"
           prompt: "Broadcast message:"
           answer: "\n"

   - name: "reset ssh connection"
     meta: reset_connection

  #  - name: "Configure description for interface in standard name"
  #    sonic_config:
  #      commands:
  #        - description Eth1/1
  #      parents:
  #        - interface Eth1/1
