---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
    - dellemc.sonic
  tasks:
    - name: "Test sonic_bgp_af Delete all 01"
      sonic_bgp_af:
        state: deleted

    - name: "Test sonic_bgp_af Delete all 02"
      sonic_bgp_af:
        state: deleted

    - name: "Test sonic_bgp_af merge afi safi 01"
      sonic_bgp_af:
        config:
          - bgp_as: 51
            vrf_name: default
            address_family:
              - afi: ipv4
                safi: unicast
        state: merged

    - name: "Test sonic_bgp_af merge afi safi 02"
      sonic_bgp_af:
        config:
          - bgp_as: 51
            vrf_name: default
            address_family:
              - afi: ipv4
                safi: unicast
        state: merged

    - name: "Test sonic_bgp_af merge 01"
      sonic_bgp_af:
        config:
          - bgp_as: 51
            vrf_name: default
            address_family:
              - afi: ipv4
                safi: unicast
                advertise_all_vni: false
                redistribute:
                  - metric: "20"
                    protocol: connected
                    route_map: aa
                  - metric: "26"
                    protocol: ospf
                    route_map: bb
                  - metric: "25"
                    protocol: static
                    route_map: aa
              - afi: ipv6
                safi: unicast
                advertise_all_vni: true
                redistribute:
                  - metric: "21"
                    protocol: connected
                    route_map: bb
                  - metric: "27"
                    protocol: ospf
                    route_map: aa
                  - metric: "28"
                    protocol: static
                    route_map: aa
              - afi: l2vpn
                safi: evpn
                advertise_all_vni: True
                advertise_default_gw: True
                advertise_prefix:
                 - afi: ipv4
                   safi: unicast
                 - afi: ipv6
                   safi: unicast
          - bgp_as: 52
            vrf_name: VrfCheck2
            address_family:
              - afi: ipv4
                safi: unicast
                redistribute:
                  - metric: "20"
                    protocol: connected
                    route_map: aa
                  - metric: "26"
                    protocol: ospf
                    route_map: bb
                  - metric: "25"
                    protocol: static
                    route_map: aa
              - afi: ipv6
                safi: unicast
                redistribute:
                  - metric: "21"
                    protocol: connected
                    route_map: bb
                  - metric: "27"
                    protocol: ospf
                    route_map: aa
                  - metric: "28"
                    protocol: static
                    route_map: aa
              - afi: l2vpn
                safi: evpn
                advertise_default_gw: True
                advertise_prefix:
                 - afi: ipv4
                   safi: unicast
                 - afi: ipv6
                   safi: unicast
        state: merged

    - name: "Test sonic_bgp_af merge 02"
      sonic_bgp_af:
        config:
          - bgp_as: 51
            vrf_name: default
            address_family:
              - afi: ipv4
                safi: unicast
                advertise_all_vni: false
                redistribute:
                  - metric: "20"
                    protocol: connected
                    route_map: aa
                  - metric: "26"
                    protocol: ospf
                    route_map: bb
                  - metric: "25"
                    protocol: static
                    route_map: aa
              - afi: ipv6
                safi: unicast
                advertise_all_vni: true
                redistribute:
                  - metric: "21"
                    protocol: connected
                    route_map: bb
                  - metric: "27"
                    protocol: ospf
                    route_map: aa
                  - metric: "28"
                    protocol: static
                    route_map: aa
              - afi: l2vpn
                safi: evpn
                advertise_all_vni: True
                advertise_default_gw: True
                advertise_prefix:
                 - afi: ipv4
                   safi: unicast
                 - afi: ipv6
                   safi: unicast
          - bgp_as: 52
            vrf_name: VrfCheck2
            address_family:
              - afi: ipv4
                safi: unicast
                redistribute:
                  - metric: "20"
                    protocol: connected
                    route_map: aa
                  - metric: "26"
                    protocol: ospf
                    route_map: bb
                  - metric: "25"
                    protocol: static
                    route_map: aa
              - afi: ipv6
                safi: unicast
                redistribute:
                  - metric: "21"
                    protocol: connected
                    route_map: bb
                  - metric: "27"
                    protocol: ospf
                    route_map: aa
                  - metric: "28"
                    protocol: static
                    route_map: aa
              - afi: l2vpn
                safi: evpn
                advertise_default_gw: True
                advertise_prefix:
                 - afi: ipv4
                   safi: unicast
                 - afi: ipv6
                   safi: unicast
        state: merged

    - name: "Test sonic_bgp_af merge specific values 01"
      sonic_bgp_af:
        config:
          - bgp_as: 51
            vrf_name: default
            address_family:
              - afi: ipv4
                safi: unicast
                advertise_all_vni: true
                redistribute:
                  - metric: "40"
                    protocol: connected
                    route_map: aa
                  - metric: "46"
                    protocol: ospf
                    route_map: bb
                  - metric: "45"
                    protocol: static
                    route_map: bb
              - afi: ipv6
                safi: unicast
                advertise_all_vni: true
                redistribute:
                  - metric: "21"
                    protocol: connected
                    route_map: bb
                  - metric: "27"
                    protocol: ospf
                    route_map: aa
                  - metric: "28"
                    protocol: static
                    route_map: aa
              - afi: l2vpn
                safi: evpn
                advertise_all_vni: False
                advertise_default_gw: True
                advertise_prefix:
                 - afi: ipv4
                   safi: unicast
        state: merged

    - name: "Test sonic_bgp_af merge specific values 02"
      sonic_bgp_af:
        config:
          - bgp_as: 51
            vrf_name: default
            address_family:
              - afi: ipv4
                safi: unicast
                advertise_all_vni: true
                redistribute:
                  - metric: "40"
                    protocol: connected
                    route_map: aa
                  - metric: "46"
                    protocol: ospf
                    route_map: bb
                  - metric: "45"
                    protocol: static
                    route_map: bb
              - afi: ipv6
                safi: unicast
                advertise_all_vni: true
                redistribute:
                  - metric: "21"
                    protocol: connected
                    route_map: bb
                  - metric: "27"
                    protocol: ospf
                    route_map: aa
                  - metric: "28"
                    protocol: static
                    route_map: aa
              - afi: l2vpn
                safi: evpn
                advertise_all_vni: False
                advertise_default_gw: True
                advertise_prefix:
                 - afi: ipv4
                   safi: unicast
        state: merged

    - name: "Test sonic_bgp_af delete specific values 01"
      sonic_bgp_af:
        config:
          - bgp_as: 51
            vrf_name: default
            address_family:
              - afi: ipv4
                safi: unicast
                advertise_all_vni: false
                redistribute:
                  - metric: "40"
                    protocol: connected
                  - protocol: ospf
                    route_map: bb
                  - metric: "45"
                    protocol: static
                    route_map: bb
              - afi: ipv6
                safi: unicast
                advertise_all_vni: true
              - afi: l2vpn
                safi: evpn
                advertise_all_vni: False
                advertise_default_gw: True
                advertise_prefix:
                 - afi: ipv4
                   safi: unicast
        state: deleted

    - name: "Test sonic_bgp_af delete specific values 02"
      sonic_bgp_af:
        config:
          - bgp_as: 51
            vrf_name: default
            address_family:
              - afi: ipv4
                safi: unicast
                advertise_all_vni: false
                redistribute:
                  - metric: "40"
                    protocol: connected
                  - protocol: ospf
                    route_map: bb
                  - metric: "45"
                    protocol: static
                    route_map: bb
              - afi: ipv6
                safi: unicast
                advertise_all_vni: true
              - afi: l2vpn
                safi: evpn
                advertise_all_vni: False
                advertise_default_gw: True
                advertise_prefix:
                 - afi: ipv4
                   safi: unicast
        state: deleted

    - name: "Test sonic_bgp_af delete specific address family 01"
      sonic_bgp_af:
        config:
          - bgp_as: 51
            vrf_name: default
            address_family:
              - afi: ipv6
                safi: unicast
        state: deleted

    - name: "Test sonic_bgp_af delete specific address family 02"
      sonic_bgp_af:
        config:
          - bgp_as: 51
            vrf_name: default
            address_family:
              - afi: ipv6
                safi: unicast
        state: deleted

    - name: "Test sonic_bgp_af delete all address family of specific bgp 01"
      sonic_bgp_af:
        config:
          - bgp_as: 52
            vrf_name: VrfCheck2
        state: deleted

    - name: "Test sonic_bgp_af delete all address family of specific bgp 02"
      sonic_bgp_af:
        config:
          - bgp_as: 52
            vrf_name: VrfCheck2
        state: deleted

    - name: "Test sonic_bgp_af Delete all 03"
      sonic_bgp_af:
        state: deleted

    - name: "Test sonic_bgp_af Delete all 04"
      sonic_bgp_af:
        state: deleted
