---
- name: "Test SONiC CLI"
  hosts: sonic2 
  gather_facts: no
  connection: httpapi
  collections:
    - dellemc.sonic
  tasks:
  - name: Test SONiC single command
    sonic_facts:
      gather_network_resources:
        - bgp_as_paths
    register: cmd_op
  - debug: var=cmd_op