---
- name: "Test SONiC CLI"
  hosts: datacenter 
  gather_facts: no
  connection: httpapi
  collections:
    - dellemc.sonic
  tasks:
  - name: Add one as_path_list
    sonic_bgp_as_paths:
      config:
        - name: test
          members:
            - "11"
            - "22"
            - "33"
        - name: test_1
          members:
            - "101.101"
            - "201.201"
            - "301.301"
      state: merged
    register: merge_as_path_list_single_output
  - name: Add one as_path_list Idempotent test
    sonic_bgp_as_paths:
      config:
        - name: test
          members: 
            - "11"
            - "22"
            - "33"
        - name: test_1
          members:
            - "101.101"
            - "201.201"
            - "301.301"    
      state: merged
    register: merge_as_path_list_single_rerun_output

  - name: Delete a single member of a as_path
    sonic_bgp_as_paths:
      config:
        - name: test
          members:
            - "11"
            - "22"
      state: deleted
    register: delete_member_as_path_list_single_output
  - name: Delete a single member of a as_path Idempotent test
    sonic_bgp_as_paths:
      config:
        - name: test
          members: 
            - "11"
            - "22"
      state: deleted
    register: delete_member_as_path_list_single_rerun_output

  - name: Delete a single as-path
    sonic_bgp_as_paths:
      config:
        - name: test_1
          members:
      state: deleted
    register: delete_single_as_path_list_single_output
  - name: Delete a single as_path Idempotent test
    sonic_bgp_as_paths:
      config:
        - name: test_1
          members:
      state: deleted
    register: delete_single_as_path_list_single_rerun_output

  - name: Delete all as-path
    sonic_bgp_as_paths:
      config:
      state: deleted
    register: delete_all_as_path_list_output
  - name: Delete all as-path Idempotent test
    sonic_bgp_as_paths:
      config:
      state: deleted
    register: delete_all_as_path_list_output_rerun_output