---

- name: "Test lag_interfaces"
  hosts: datacenter
  gather_facts: no
  connection: httpapi
  collections:
    - dellemc.sonic
  tasks:

  - name: Test sonic_lag_interfaces 'deleted all' in "delete" state
    sonic_lag_interfaces:
      config:
      state: deleted
    register: delete_all_output
  - name: Test sonic_lag_interfaces "delete_all" idempotency
    sonic_lag_interfaces:
      config:
      state: deleted
    register: delete_all_idempotent_output
  - name: Test sonic_lag_interfaces "merged" state
    sonic_lag_interfaces:
      config:
        - name: PortChannel12
          members:
            interfaces:
              - member: Ethernet56
              - member: Ethernet68
        - name: PortChannel1
          members:
            interfaces:
              - member: Ethernet24
        - name: PortChannel2
      state: merged
    register: merge_output
  - name: Test sonic_lag_interfaces "merged" idempotency
    sonic_lag_interfaces:
      config:
        - name: PortChannel12
          members:
            interfaces:
              - member: Ethernet56
              - member: Ethernet68
        - name: PortChannel1
          members:
            interfaces:
              - member: Ethernet24
        - name: PortChannel2
      state: merged
    register: merge_idempotent_output
  - name: Test sonic_lag_interfaces "deleted" state
    sonic_lag_interfaces:
      config:
        - name: PortChannel12
          members:
            interfaces:
              - member: Ethernet56
        - name: PortChannel2
      state: deleted
    register: deleted_output
  - name: Test sonic_lag_interfaces "deleted" state idempotency
    sonic_lag_interfaces:
      config:
        - name: PortChannel12
          members:
            interfaces:
              - member: Ethernet56
      state: deleted
    ignore_errors: yes
    register: deleted_idempotent_output
  - name: Test sonic_lag_interfaces "overridden" state 
    sonic_lag_interfaces:
      config:
        - name: PortChannel10
          members:
            interfaces:
              - member: Ethernet4
              - member: Ethernet8
        - name: PortChannel1
          members:
            interfaces:
              - member: Ethernet64
      state: overridden
    register: overridden_output
  - name: Test sonic_lag_interfaces "overridden" state idempotency
    sonic_lag_interfaces:
      config:
        - name: PortChannel10
          members:
            interfaces:
        - name: PortChannel1
          members:
            interfaces:
              - member: Ethernet64
      state: overridden
    register: overridden_idempotent_output
  - name: Test sonic_lag_interfaces "replaced" state
    sonic_lag_interfaces:
      config:
        - name: PortChannel1
          members:
            interfaces:
              - member: Ethernet24
        - name: PortChannel10
          members:
            interfaces:
              - member: Ethernet44
              - member: Ethernet32
        - name: PortChannel29
      state: replaced
    register: replaced_output
  - name: Test sonic_lag_interfaces "replaced" state idempotency
    sonic_lag_interfaces:
      config:
        - name: PortChannel1
          members:
            interfaces:
              - member: Ethernet24
        - name: PortChannel10
          members:
            interfaces:
              - member: Ethernet44
              - member: Ethernet32
        - name: PortChannel29
      state: replaced
    register: replaced_idempotent_output
