---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
    - dellemc.sonic
  tasks:
    - name: "Test sonic_l2_interfaces merged state"
      sonic_l2_interfaces:
        config:
          - name: Ethernet20
            access: 
              vlan: 12
          - name: Ethernet28
            access: 
              vlan: 11
            trunk: 
              allowed_vlans:
                - vlan: 12
                - vlan: 13
        state: merged
