---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
    - dellemc.sonic
  tasks:
    - name: "Test sonic_bgp Delete all 01"
      sonic_bgp:
        state: deleted

    - name: "Test sonic_bgp Delete all 02"
      sonic_bgp:
        state: deleted

    - name: "Test sonic_bgp merge 01"
      sonic_bgp:
        config:
            - bgp_as: 4
              router_id: 10.2.2.4
              log_neighbor_changes: False
              bestpath:
                as_path:
                  confed: True
                  ignore: True
                  multipath_relax: False
                  multipath_relax_as_set: True
                compare_routerid: True
                med:
                  confed: True
                  missing_as_worst: True
            - bgp_as: 11
              router_id: 10.2.2.32
              log_neighbor_changes: True
              vrf_name: 'VrfCheck1'
              bestpath:
                as_path:
                  confed: False
                  ignore: True
                  multipath_relax_as_set: True
                compare_routerid: True
                med:
                  confed: True
                  missing_as_worst: True
        state: merged

    - name: "Test sonic_bgp merge 02"
      sonic_bgp:
        config:
            - bgp_as: 4
              router_id: 10.2.2.4
              log_neighbor_changes: False
              bestpath:
                as_path:
                  confed: True
                  ignore: True
                  multipath_relax: False
                  multipath_relax_as_set: True
                compare_routerid: True
                med:
                  confed: True
                  missing_as_worst: True
            - bgp_as: 11
              router_id: 10.2.2.32
              log_neighbor_changes: True
              vrf_name: 'VrfCheck1'
              bestpath:
                as_path:
                  confed: False
                  ignore: True
                  multipath_relax_as_set: True
                compare_routerid: True
                med:
                  confed: True
                  missing_as_worst: True
        state: merged

    - name: "Test sonic_bgp merge specifig params 01"
      sonic_bgp:
        config:
            - bgp_as: 4
              router_id: 10.2.2.5
              log_neighbor_changes: True
              bestpath:
                as_path:
                  confed: False
                  ignore: True
                  multipath_relax: True
                  multipath_relax_as_set: False
                compare_routerid: True
                med:
                  confed: True
                  missing_as_worst: False
            - bgp_as: 11
              router_id: 10.2.2.33
              log_neighbor_changes: False
              vrf_name: 'VrfCheck1'
              bestpath:
                as_path:
                  confed: True
                  ignore: False
                  multipath_relax_as_set: True
                compare_routerid: False
                med:
                  confed: False
                  missing_as_worst: False
        state: merged

    - name: "Test sonic_bgp merge specifig params 02"
      sonic_bgp:
        config:
            - bgp_as: 4
              router_id: 10.2.2.5
              log_neighbor_changes: True
              bestpath:
                as_path:
                  confed: False
                  ignore: True
                  multipath_relax: True
                  multipath_relax_as_set: False
                compare_routerid: True
                med:
                  confed: True
                  missing_as_worst: False
            - bgp_as: 11
              router_id: 10.2.2.33
              log_neighbor_changes: False
              vrf_name: 'VrfCheck1'
              bestpath:
                as_path:
                  confed: True
                  ignore: False
                  multipath_relax_as_set: True
                compare_routerid: False
                med:
                  confed: False
                  missing_as_worst: False
        state: merged

    - name: "Test sonic_bgp merge specifig param and new 01"
      sonic_bgp:
        config:
            - bgp_as: 4
              router_id: 10.2.2.3
              log_neighbor_changes: False
            - bgp_as: 12
              router_id: 10.2.2.64
              log_neighbor_changes: True
              vrf_name: 'VrfCheck2'
        state: merged

    - name: "Test sonic_bgp merge specifig param and new 02"
      sonic_bgp:
        config:
            - bgp_as: 4
              router_id: 10.2.2.3
              log_neighbor_changes: False
            - bgp_as: 12
              router_id: 10.2.2.64
              log_neighbor_changes: True
              vrf_name: 'VrfCheck2'
        state: merged

    - name: "Test sonic_bgp delete specifig param 01"
      sonic_bgp:
        config:
            - bgp_as: 4
              router_id: 10.2.2.3
              log_neighbor_changes: False
              bestpath:
                as_path:
                  confed: False
                  ignore: True
                  multipath_relax: True
                  multipath_relax_as_set: False
                compare_routerid: True
                med:
                  confed: True
                  missing_as_worst: False
            - bgp_as: 11
              router_id: 10.2.2.33
              log_neighbor_changes: False
              vrf_name: 'VrfCheck1'
              bestpath:
                as_path:
                  confed: True
                  ignore: False
                  multipath_relax_as_set: True
                compare_routerid: False
                med:
                  confed: False
                  missing_as_worst: False
            - bgp_as: 12
              router_id: 10.2.2.64
              log_neighbor_changes: True
              vrf_name: 'VrfCheck2'
        state: deleted

    - name: "Test sonic_bgp delete specifig param 02"
      sonic_bgp:
        config:
            - bgp_as: 4
              router_id: 10.2.2.3
              log_neighbor_changes: False
              bestpath:
                as_path:
                  confed: False
                  ignore: True
                  multipath_relax: True
                  multipath_relax_as_set: False
                compare_routerid: True
                med:
                  confed: True
                  missing_as_worst: False
            - bgp_as: 11
              router_id: 10.2.2.33
              log_neighbor_changes: False
              vrf_name: 'VrfCheck1'
              bestpath:
                as_path:
                  confed: True
                  ignore: False
                  multipath_relax_as_set: True
                compare_routerid: False
                med:
                  confed: False
                  missing_as_worst: False
            - bgp_as: 12
              router_id: 10.2.2.64
              log_neighbor_changes: True
              vrf_name: 'VrfCheck2'
        state: deleted

    - name: "Test sonic_bgp delete specifig bgp 01"
      sonic_bgp:
        config:
            - bgp_as: 4
            - bgp_as: 11
              vrf_name: 'VrfCheck1'
            - bgp_as: 12
              vrf_name: 'VrfCheck2'
        state: deleted

    - name: "Test sonic_bgp delete specifig bgp 02"
      sonic_bgp:
        config:
            - bgp_as: 4
            - bgp_as: 11
              vrf_name: 'VrfCheck1'
            - bgp_as: 12
              vrf_name: 'VrfCheck2'
        state: deleted

    - name: "Test sonic_bgp delete specifig bgp 01"
      sonic_bgp:
        config:
            - bgp_as: 4
            - bgp_as: 11
              vrf_name: 'VrfCheck1'
            - bgp_as: 12
              vrf_name: 'VrfCheck2'
        state: merged

    - name: "Test sonic_bgp delete specifig bgp 02"
      sonic_bgp:
        config:
            - bgp_as: 4
            - bgp_as: 11
              vrf_name: 'VrfCheck1'
            - bgp_as: 12
              vrf_name: 'VrfCheck2'
        state: merged

    - name: "Test sonic_bgp Delete all 03"
      sonic_bgp:
        state: deleted

    - name: "Test sonic_bgp Delete all 04"
      sonic_bgp:
        state: deleted
