---
namespace: dellemc
name: enterprise_sonic
version: 3.2.0
readme: README.md
authors:
  - Senthil Kumar Ganesan <Senthil_Kumar_Ganesa@Dell.com>
  - Abirami <Abirami_N@Dell.com>
  - Dhivya <Dhivya_P@Dell.com>
  - Mohamed Javeed <Mohamed_Javeed_Faroo@Dell.com>
  - Nirai Madai <Niraimadaiselvam_Mar@Dell.com>
  - S. Talabi <Shade_Talabi@Dell.com>
  - Kerry Meyer <Kerry_Meyer@Dell.com>
  - Mingjun Zhang <Mingjun_Zhang@Dell.com>
  - Arun Saravanan Balachandran (arun_saravanan_balac@dell.com)
  - Santhosh Kumar T (santhosh_kumar_t@dell.com)
  - Divya Balasubramanian <Divya_Balasubramania@DELL.com>
  - Cypher Miller <Cypher.Miller@Dell.com>

description: Ansible Network Collection for Enterprise SONiC Distribution by Dell Technologies
license_file: LICENSE
tags: [dellemc, dell, networking, nos, sonic]
dependencies:
  "ansible.netcommon": ">=8.1.0"
repository: https://github.com/ansible-collections/dellemc.enterprise_sonic
issues: https://github.com/ansible-collections/dellemc.enterprise_sonic/issues
