namespace: dellemc
name: sonic
version: 1.0.2
readme: README.md
authors:
- Senthil Kumar Ganesan <Senthil_Kumar_Ganesa@Dell.com>
- Abirami <Abirami_N@Dell.com>
- Dhivya <Dhivya_P@Dell.com>
- Mohamed Javeed <Mohamed_Javeed_Faroo@Dell.com>
- Nirai Madai <Niraimadaiselvam_Mar@Dell.com>
 
description: Ansible Network Collection for Enterprise SONiC Distribution by Dell Technologies
license_file: LICENSE
tags: [dellemc, dell, networking, onos, nos, sonic]
dependencies: 
  "ansible.netcommon": '>=1.0.0'
repository: https://github.com/ansible-collections/dellemc.sonic
issues: https://github.com/ansible-collections/dellemc.sonic/issues 
