---
bugfixes:
  - sonic_ospfv2 - Fix the sonic_ospfv2 Ansible module so that it can correctly configure protocol‑only redistribution for OSPFv2 (https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/630).
