#
# -*- coding: utf-8 -*-
# Copyright 2019 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the sonic_bgp_neighbors module
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type


class Bgp_neighborsArgs(object):  # pylint: disable=R0903
    """The arg spec for the sonic_bgp_neighbors module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {
        'config': {
            'elements': 'dict',
            'options': {
                'bgp_as': {'required': True, 'type': 'str'},
                'neighbors': {
                    'elements': 'dict',
                    'options': {
                        'description': {'type': 'str'},
                        'ebgp_multihop': {'type': 'int'},
                        'enabled': {'type': 'bool'},
                        'local_as': {'type': 'int'},
                        'neighbor': {'required': True, 'type': 'str'},
                        'password': {'type': 'str'},
                        'peer_group': {'type': 'str'},
                        'remote_as': {'required': True, 'type': 'int'},
                        'timers': {
                            'options': {
                                'holdtime': {'required': True, 'type': 'int'},
                                'keepalive': {'required': True, 'type': 'int'}
                            },
                            'type': 'dict'
                        },
                        'update_source': {'type': 'str'}
                    },
                    'type': 'list'
                },
                'peergroup': {
                    'elements': 'dict',
                    'options': {
                        'name': {'type': 'str'}
                    },
                    'type': 'list'
                },
                'vrf_name': {'default': 'default', 'type': 'str'}
            },
            'type': 'list'
        },
        'state': {
            'choices': ['merged', 'deleted'],
            'default': 'merged'
        }
    }  # pylint: disable=C0301
