#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2019 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for sonic_bgp_neighbors_af
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: sonic_bgp_neighbors_af
version_added: "2.10"
author: "Dhivya P (@dhivayp)"
short_description: Configure global BGP protocol settings on SONiC.
description:
  - This module provides configuration management of global BGP parameters
    on devices running SONiC
notes:
  - Tested against SONiC Version 3.0.1
options:
  config:
    description:
      - Specifies the BGP related configuration.
    type: list
    elements: dict
    suboptions:
      bgp_as:
        description:
          - Specifies the BGP Autonomous System (AS) number to configure on the device.
        type: str
        required: true
      vrf_name:
        description:
          - Specifies the vrf name
        type: str
        default: 'default'
      address_family:
        description:
          - Specifies BGP address family related configurations.
        type: list
        elements: dict
        suboptions:
          afi:
            description:
              - Type of address family to configure.
            type: str
            choices:
              - ipv4
              - ipv6
            required: True
          safi:
            description:
             - Specifies the type of cast for the address family.
            type: str
            choices:
              - unicast
              - evpn
            default: unicast
          neighbors:
            description:
              - Specifies BGP neighbor related configurations in Address Family configuration mode.
            type: list
            elements: dict
            suboptions:
              neighbor:
                description:
                  - Neighbor router address.
                type: str
                required: True
              activate:
                description:
                  - Enable the Address Family for this Neighbor.
                type: bool
              allowas_in:
                description:
                  - Specify the allow as in values
                type: dict
                suboptions:
                  value:
                    description:
                      - Specify the value of the allowas in
                    type: int
                  origin:
                    description:
                      - Specify the origin value
                    type: bool
              route_map:
                description:
                  - Specify the route map
                type: list
                elements: dict
                suboptions:
                  name:
                    description:
                      - Specify the name of the route map
                    type: str
                  direction:
                    description:
                      - Specify the direction of the route map
                    type: str
              route_reflector_client:
                description:
                  - Specify a neighbor as a route reflector client.
                type: bool
              route_server_client:
                description:
                  - Specify a neighbor as a route server client.
                type: bool
              remove_private_as:
                description:
                  - Remove the private AS number from outbound updates.
                type: bool
              next_hop_self:
                description:
                  - Enable/disable the next hop calculation for this neighbor.
                type: bool
              maximum_prefix:
                description:
                  - Maximum number of prefixes to accept from this peer.
                  - The range is from 1 to 2147483647.
                type: int
              prefix_list_in:
                description:
                  - Name of ip prefix-list to apply to incoming prefixes.
                type: str
              prefix_list_out:
                description:
                  - Name of ip prefix-list to apply to outgoing prefixes.
                type: str
  state:
    description:
      - Specifies the operation to be performed on the BGP process configured on the device.
      - In case of merged, the input configuration will be merged with the existing BGP configuration on the device.
      - In case of deleted the existing BGP configuration will be removed from the device.
    default: merged
    choices: ['merged', 'deleted']
"""
EXAMPLES = """
# Using deleted

# Before state:
# -------------
#
# interface Ethernet40
#   channel-group 10

- name: Delete LAG attributes of given interface (Note: This won't delete the port-channel itself).
  sonic_lag_interfaces:
    config:
      - name: PortChannel10
    state: deleted

# After state:
# ------------
#
# interface Ethernet40
#   no channel-group


# Using merged

# Before state:
# -------------
#
# interface Ethernet40
# interface Ethernet60
#   channel-group 12

- name: Merge provided configuration with device configuration.
  sonic_lag_interfaces:
    config:
      - name: PortChannel10
        members:
          interfaces:
            - member: Ethernet40
    state: merged

# After state:
# ------------
#
# interface Ethernet40
#   channel-group 10
# interface Ethernet60
#   channel-group 12


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.dellemc.sonic.plugins.module_utils.network.sonic.argspec.bgp_neighbors_af.bgp_neighbors_af import Bgp_neighbors_afArgs
from ansible_collections.dellemc.sonic.plugins.module_utils.network.sonic.config.bgp_neighbors_af.bgp_neighbors_af import Bgp_neighbors_af


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=Bgp_neighbors_afArgs.argument_spec,
                           supports_check_mode=True)

    result = Bgp_neighbors_af(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
