#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2019 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for sonic_bgp_af
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: sonic_bgp_af
version_added: "2.10"
author: "Dhivya P (@dhivayp)"
short_description: Configure global BGP_AF protocol settings on SONiC.
description:
  - This module provides configuration management of global BGP_AF parameters
    on devices running SONiC
notes:
  - Tested against SONiC Version 3.0.1
options:
  config:
    description:
      - Specifies the BGP_AF related configuration.
    type: list
    elements: dict
    suboptions:
      bgp_as:
        description:
          - Specifies the BGP Autonomous System (AS) number to configure on the device.
        type: str
        required: true
      vrf_name:
        description:
          - Specifies the vrf name
        type: str
        default: 'default'
      address_family:
        description:
          - Specifies BGP address family related configurations.
        type: list
        elements: dict
        suboptions:
          afi:
            description:
              - Type of address family to configure.
            type: str
            choices:
              - ipv4
              - ipv6
              - l2vpn
            required: True
          safi:
            description:
             - Specifies the type of cast for the address family.
            type: str
            choices:
              - unicast
              - evpn
            default: unicast
          redistribute:
            description:
              - Specifies the redistribute information from another routing protocol.
            type: list
            elements: dict
            suboptions:
              protocol:
                description:
                  - Specifies the protocol for configuring redistribute information.
                type: str
                choices: ['ospf', 'static', 'connected']
                required: True
              metric:
                description:
                  - Specifies the metric for redistributed routes.
                type: str
              route_map:
                description:
                  - Specifies the route map reference.
                type: str
          advertise_prefix:
            description:
              - Specifies the prefix of the advertise
            type: list
            elements: dict
            suboptions:
              afi:
                description:
                  - Specifies afi of the advertise
                type: str
                choices:
                  - ipv4
                  - ipv6
                  - l2vpn
              safi:
                description:
                  - Specifies safi of the advertise
                type: str
                choices:
                  - unicast
                  - evpn
                default: unicast
          advertise_default_gw:
            description:
              - Specifies the advertise default gateway flag
            type: bool
          advertise_all_vni:
            description:
              - Specifies the advertise all vni flag
            type: bool
  state:
    description:
      - Specifies the operation to be performed on the BGP_AF process configured on the device.
      - In case of merged, the input configuration will be merged with the existing BGP_AF configuration on the device.
      - In case of deleted the existing BGP_AF configuration will be removed from the device.
    default: merged
    choices: ['merged', 'deleted']
"""
EXAMPLES = """
# Using deleted
#
# Before state:
# -------------
#
#!
#router bgp 4
#!
#address-family ipv4 unicast
# redistribute connected route-map bb metric 21
# redistribute ospf route-map aa metric 27
# redistribute static route-map bb metric 26
#!
#address-family ipv6 unicast
#!
#address-family l2vpn evpn
# advertise ipv4 unicast
# advertise ipv6 unicast
#!
#
#- name: Delete LAG attributes of given interface (Note: This won't delete the port-channel itself).
#      sonic_bgp:
#        config:
#          - bgp_as: 4
#            address_family:
#              - afi: l2vpn
#                safi: evpn
#                advertise_all_vni: False
#                advertise_default_gw: False
#                advertise_prefix:
#                 - afi: ipv4
#                   safi: unicast
#              - afi: ipv6
#                safi: unicast
#              - afi: ipv4
#                safi: unicast
#                redistribute:
#                  - metric: "21"
#                    protocol: connected
#                    route_map: bb
#                  - metric: "27"
#                    protocol: ospf
#                    route_map: aa
#                  - metric: "26"
#                    protocol: static
#                    route_map: bb
#        state: deleted
# After state:
# ------------
#
#!
#router bgp 4
# !
# address-family ipv4 unicast
# !
# address-family l2vpn evpn
#  advertise ipv6 unicast
#!


# Using deleted
#
# Before state:
# -------------
#
#!
#router bgp 4
#!
#address-family ipv4 unicast
# redistribute connected route-map bb metric 21
# redistribute ospf route-map aa metric 27
# redistribute static route-map bb metric 26
#!
#address-family ipv6 unicast
#!
#address-family l2vpn evpn
# advertise ipv4 unicast
# advertise ipv6 unicast
#!
#
#- name: Delete LAG attributes of given interface (Note: This won't delete the port-channel itself).
#      sonic_bgp:
#        config:
#          - bgp_as: 4
#        state: deleted
# After state:
# ------------
#
#!
#router bgp 4
#!


# Using deleted
#
# Before state:
# -------------
#
#!
#router bgp 4
#!
#address-family ipv4 unicast
#!
#
#- name: Delete LAG attributes of given interface (Note: This won't delete the port-channel itself).
#      sonic_bgp:
#        config:
#          - bgp_as: 4
#            address_family:
#              - afi: l2vpn
#                safi: evpn
#                advertise_all_vni: False
#                advertise_default_gw: False
#                advertise_prefix:
#                 - afi: ipv4
#                   safi: unicast
#                 - afi: ipv6
#                   safi: unicast
#              - afi: ipv6
#                safi: unicast
#              - afi: ipv4
#                safi: unicast
#                redistribute:
#                  - metric: "21"
#                    protocol: connected
#                    route_map: bb
#                  - metric: "27"
#                    protocol: ospf
#                    route_map: aa
#                  - metric: "26"
#                    protocol: static
#                    route_map: bb
#        state: merged
# After state:
# ------------
#
#!
#router bgp 4
#!
#address-family ipv4 unicast
# redistribute connected route-map bb metric 21
# redistribute ospf route-map aa metric 27
# redistribute static route-map bb metric 26
#!
#address-family ipv6 unicast
#!
#address-family l2vpn evpn
# advertise ipv4 unicast
# advertise ipv6 unicast
#!


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.dellemc.sonic.plugins.module_utils.network.sonic.argspec.bgp_af.bgp_af import Bgp_afArgs
from ansible_collections.dellemc.sonic.plugins.module_utils.network.sonic.config.bgp_af.bgp_af import Bgp_af


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=Bgp_afArgs.argument_spec,
                           supports_check_mode=True)

    result = Bgp_af(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
