#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2019 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for sonic_bgp
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'community',
    'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: sonic_bgp
version_added: "2.10"
author: "Dhivya P (@dhivayp)"
short_description: Configure global BGP protocol settings on SONiC.
description:
  - This module provides configuration management of global BGP parameters on devices running SONiC
notes:
  - Tested against SONiC Version 3.0.1
options:
  config:
    description:
      - Specifies the BGP related configuration.
    type: list
    elements: dict
    suboptions:
      bgp_as:
        description:
          - Specifies the BGP Autonomous System (AS) number to configure on the device.
        type: str
        required: true
      vrf_name:
        description:
          - Specifies the vrf name
        type: str
        default: 'default'
      router_id:
        description:
          - Configures the BGP routing process router-id value.
        type: str
      log_neighbor_changes:
        description:
          - Enable/disable logging neighbor up/down and reset reason.
        type: bool
      bestpath:
        description:
          - Configures the BGP bestpath.
        type: dict
        suboptions:
          as_path:
            description:
              - Configure the as_path values
            type: dict
            suboptions:
              confed:
                description:
                  - Configure the confed values of as-path
                type: bool
              ignore:
                description:
                  - Configure the ignore values of as-path
                type: bool
              multipath_relax:
                description:
                  - Configure the multipath_relax values of as-path
                type: bool
              multipath_relax_as_set:
                description:
                  - Configure the multipath_relax_as_set values of as-path
                type: bool
          compare_routerid:
            description:
              - Configures the compare_routerid.
            type: bool
          med:
            description:
              - Configure the med values
            type: dict
            suboptions:
              confed:
                description:
                  - Configure the confed values of med
                type: bool
              missing_as_worst:
                description:
                  - Configure the missing_as_worst values of as-path
                type: bool
  state:
    description:
      - Specifies the operation to be performed on the BGP process configured on the device.
      - In case of merged, the input configuration will be merged with the existing BGP configuration on the device.
      - In case of deleted the existing BGP configuration will be removed from the device.
    default: merged
    choices: ['merged', 'deleted']
"""
EXAMPLES = """
# Using deleted
#
# Before state:
# -------------
#
#!
#router bgp 10 vrf VrfCheck1
# router-id 10.2.2.32
# log-neighbor-changes
#!
#router bgp 11 vrf VrfCheck2
# log-neighbor-changes
# bestpath as-path ignore
# bestpath med missing-as-worst confed
# bestpath compare-routerid
#!
#router bgp 4
# router-id 10.2.2.4
# bestpath as-path ignore
# bestpath as-path confed
# bestpath med missing-as-worst confed
# bestpath compare-routerid
#!
#
#- name: Delete LAG attributes of given interface (Note: This won't delete the port-channel itself).
#      sonic_bgp:
#        config:
#            - bgp_as: 4
#              router_id: 10.2.2.4
#              log_neighbor_changes: False
#              bestpath:
#                as_path:
#                  confed: True
#                  ignore: True
#                  multipath_relax: False
#                  multipath_relax_as_set: True
#                compare_routerid: True
#                med:
#                  confed: True
#                  missing_as_worst: True
#            - bgp_as: 10
#              router_id: 10.2.2.32
#              log_neighbor_changes: True
#              vrf_name: 'VrfCheck1'
#            - bgp_as: 11
#              log_neighbor_changes: True
#              vrf_name: 'VrfCheck2'
#              bestpath:
#                as_path:
#                  confed: False
#                  ignore: True
#                  multipath_relax_as_set: True
#                compare_routerid: True
#                med:
#                  confed: True
#                  missing_as_worst: True
#        state: deleted
# After state:
# ------------
#
#!
#router bgp 10 vrf VrfCheck1
# log-neighbor-changes
#!
#router bgp 11 vrf VrfCheck2
# log-neighbor-changes
# bestpath compare-routerid
#!
#router bgp 4
# log-neighbor-changes
# bestpath compare-routerid
#!


# Using deleted
#
# Before state:
# -------------
#
#!
#router bgp 10 vrf VrfCheck1
# router-id 10.2.2.32
# log-neighbor-changes
#!
#router bgp 11 vrf VrfCheck2
# log-neighbor-changes
# bestpath as-path ignore
# bestpath med missing-as-worst confed
# bestpath compare-routerid
#!
#router bgp 4
# router-id 10.2.2.4
# bestpath as-path ignore
# bestpath as-path confed
# bestpath med missing-as-worst confed
# bestpath compare-routerid
#!
#
#- name: Delete LAG attributes of given interface (Note: This won't delete the port-channel itself).
#      sonic_bgp:
#        config:
#        state: deleted
# After state:
# ------------
#
#!
#!


# Using merged
#
# Before state:
# -------------
#
#!
#router bgp 4
# router-id 10.1.1.4
#!
#
#- name: Merge provided configuration with device configuration.
#      sonic_bgp:
#        config:
#            - bgp_as: 4
#              router_id: 10.2.2.4
#              log_neighbor_changes: False
#              bestpath:
#                as_path:
#                  confed: True
#                  ignore: True
#                  multipath_relax: False
#                  multipath_relax_as_set: True
#                compare_routerid: True
#                med:
#                  confed: True
#                  missing_as_worst: True
#            - bgp_as: 10
#              router_id: 10.2.2.32
#              log_neighbor_changes: True
#              vrf_name: 'VrfCheck1'
#            - bgp_as: 11
#              log_neighbor_changes: True
#              vrf_name: 'VrfCheck2'
#              bestpath:
#                as_path:
#                  confed: False
#                  ignore: True
#                  multipath_relax_as_set: True
#                compare_routerid: True
#                med:
#                  confed: True
#                  missing_as_worst: True
#        state: merged
#
# After state:
# ------------
#
#!
#router bgp 10 vrf VrfCheck1
# router-id 10.2.2.32
# log-neighbor-changes
#!
#router bgp 11 vrf VrfCheck2
# log-neighbor-changes
# bestpath as-path ignore
# bestpath med missing-as-worst confed
# bestpath compare-routerid
#!
#router bgp 4
# router-id 10.2.2.4
# bestpath as-path ignore
# bestpath as-path confed
# bestpath med missing-as-worst confed
# bestpath compare-routerid
#!


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.dellemc.sonic.plugins.module_utils.network.sonic.argspec.bgp.bgp import BgpArgs
from ansible_collections.dellemc.sonic.plugins.module_utils.network.sonic.config.bgp.bgp import Bgp


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=BgpArgs.argument_spec,
                           supports_check_mode=True)

    result = Bgp(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
