#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for sonic_vlan_mapping
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
  'metadata_version': '1.1',
  'status': ['preview'],
  'supported_by': 'community',
  'license': 'Apache 2.0'
}

DOCUMENTATION = """
---
module: sonic_vlan_mapping
author: "Cypher Miller (@Cypher-Miller)"
version_added: "2.1.0"
short_description: Configure vlan mappings on SONiC.
description:
  - This module provides configuration management for vlan mappings on devices running SONiC.
  - Vlan mappings only available on TD3 and TD4 devices.
  - For TD4 devices must enable vlan mapping first.
options:
  config:
    description:
      - Specifies the vlan mapping related configuration.
    type: list
    elements: dict
    suboptions:
      name:
        description:
          - Full name of the interface, i.e. Ethernet8.
        required: true
        type: str
      mapping:
        description:
          - Defining a single vlan mapping
        type: list
        elements: dict
        suboptions:
          vlan_ids:
            description:
              - (-) or (,) separated individual VLAN IDs and ranges of VLAN IDs; for example, 20,70-100,142. If mode is set to translation only a single VLAN ID should be passed. VLAN IDs range is 1-4094.
            required: true
            type: str
          mapped_id:
            description:
              - Set the VLAN that the incoming traffic is mapped to. VLAN IDs range is 1-4094.
            required: true
            type: int
          dot1q_tunnel:
            description:
              - Specify whether it is a vlan stacking or translation (false means translation; true means stacking).
            required: false
            type: bool
            default: false
          inner_vlan:
            description:
              - Set an inner VLAN ID (Only should be used for vlan translations). VLAN IDs range is 1-4094.
            required: false
            type: int
          priority:
            description:
              - Set priority level of the vlan mapping. Priority range is 0-7.
            required: false
            type: int

state:
  description:
    - Specifies the operation to be performed on the vlan mapping configured on the device.
    - In case of merged, the input configuration will be merged with the existing vlan mappings on the device.
    - In case of deleted, the existing vlan mapping configuration will be removed from the device.
    - In case of overridden, all existing vlan mappings will be deleted and the specified input configuration will be added.
    - In case of replaced, the existing vlan mappings on the device will be replaced by the configuration in the playbook for each vlan mapping configured by the playbook.
  default: merged
  choices: ['merged', 'deleted','replaced', 'overridden']
"""
EXAMPLES = """
# Using deleted
#
# Before State:
# -------------
#
#sonic# show running-configuration interface
#!
#interface Ethernet8
# mtu 9100
# speed 400000
# fec RS
# unreliable-los auto
# shutdown
# switchport vlan-mapping 623 2411
# switchport vlan-mapping 392 inner 590 2755
#!
#interface Ethernet16
# mtu 9100
# speed 400000
# fec RS
# unreliable-los auto
# shutdown
# switchport vlan-mapping 400-402,404,406,408,410,412,420,422,430-431 dot1q-tunnel 2436
# switchport vlan-mapping 300 dot1q-tunnel 2567 priority 3
#!

  - name: Delete vlan mapping configurations
    sonic_vlan_mapping:
      config:
        - name: 'Ethernet8'
          mapping:
            - vlan_ids: '392'
              mapped_id: 2755
              dot1q_tunnel: false
              inner_vlan: 590
        - name: 'Ethernet16'
          mapping:
            - vlan_ids: '300'
              mapped_id: 2567
              dot1q_tunnel: true
              priority: 3
      state: deleted

# After State:
# ------------
#
#sonic# show running-configuration interface
#!
#interface Ethernet8
# mtu 9100
# speed 400000
# fec RS
# unreliable-los auto
# shutdown
# switchport vlan-mapping 623 2411
#!
#interface Ethernet16
# mtu 9100
# speed 400000
# fec RS
# unreliable-los auto
# shutdown
# switchport vlan-mapping 400-402,404,406,408,410,412,420,422,430-431 dot1q-tunnel 2436
#!


# Using merged
#
# Before State:
# -------------
#
#sonic# show running-configuration interface
#!
#interface Ethernet8
# mtu 9100
# speed 400000
# fec RS
# unreliable-los auto
# shutdown
# switchport vlan-mapping 623 2411
#!
#interface Ethernet16
# mtu 9100
# speed 400000
# fec RS
# unreliable-los auto
# shutdown
#!

  - name: Add vlan mapping configurations
    sonic_vlan_mapping:
      config:
        - name: 'Ethernet8'
          mapping:
            - vlan_ids: '392'
              mapped_id: 2755
              dot1q_tunnel: false
              inner_vlan: 590 
        - name: 'Ethernet16'
          mapping:
            - vlan_ids: '300'
              mapped_id: 2567
              dot1q_tunnel: true
              priority: 3
          mapping:
            - vlan_ids: '400-402,404,410,412,431,406,408,420,422,430'
              mapped_id: 2436
              dot1q_tunnel: true
        - name: Portchannel 2
          mapping:
            - vlan_ids: '345'
              mapped_id: 2999
              priority: 0
      state: merged

# After State:
# ------------
#
#sonic# show running-configuration interface
#!
#interface Ethernet8
# mtu 9100
# speed 400000
# fec RS
# unreliable-los auto
# shutdown
# switchport vlan-mapping 623 2411
# switchport vlan-mapping 392 inner 590 2755
#!
#interface Ethernet16
# mtu 9100
# speed 400000
# fec RS
# unreliable-los auto
# shutdown
# switchport vlan-mapping 400-402,404,406,408,410,412,420,422,430-431 dot1q-tunnel 2436
# switchport vlan-mapping 300 dot1q-tunnel 2567 priority 3
#!
#interface PortChannel 2
# switchport vlan-mapping 345 2999 priority 0
# no shutdown
#!


# Using replaced
#
# Before State:
# -------------
#
#sonic# show running-configuration interface
#!
#interface Ethernet8
# mtu 9100
# speed 400000
# fec RS
# unreliable-los auto
# shutdown
# switchport vlan-mapping 623 2411
# switchport vlan-mapping 392 inner 590 2755
#!
#interface Ethernet16
# mtu 9100
# speed 400000
# fec RS
# unreliable-los auto
# shutdown
# switchport vlan-mapping 400-402,404,406,408,410,412,420,422,430-431 dot1q-tunnel 2436
# switchport vlan-mapping 300 dot1q-tunnel 2567 priority 3
#!
#interface PortChannel 2
# switchport vlan-mapping 345 2999 priority 0
# no shutdown
#!

  - name: Replace vlan mapping configurations
    sonic_vlan_mapping:
      config:
        - name: 'Ethernet8'
          mapping:
            - vlan_ids: '390'
              mapped_id: 2755
              dot1q_tunnel: false
              inner_vlan: 593
        - name: 'Ethernet16'
          mapping:
          - vlan_ids: '300,302'
            mapped_id: 2567
            dot1q_tunnel: true
            priority: 5
        - name: Portchannel 2
          mapping:
          - vlan_ids: '345'
            mapped_id: 2999
            priority: 1
      state: replaced

# After State:
# ------------
#
#sonic# show running-configuration interface
#!
#interface Ethernet8
# mtu 9100
# speed 400000
# fec RS
# unreliable-los auto
# shutdown
# switchport vlan-mapping 623 2411
# switchport vlan-mapping 390 inner 593 2755
#!
#interface Ethernet16
# mtu 9100
# speed 400000
# fec RS
# unreliable-los auto
# shutdown
# switchport vlan-mapping 400-402,404,406,408,410,412,420,422,430-431 dot1q-tunnel 2436
# switchport vlan-mapping 300,302 dot1q-tunnel 2567 priority 5
#!
#interface PortChannel 2
# switchport vlan-mapping 345 2999 priority 1
# no shutdown
#!


# Using overridden
#
# Before State:
# -------------
#
#sonic# show running-configuration interface
#!
#interface Ethernet8
# mtu 9100
# speed 400000
# fec RS
# unreliable-los auto
# shutdown
# switchport vlan-mapping 623 2411
#!
#interface Ethernet16
# mtu 9100
# speed 400000
# fec RS
# unreliable-los auto
# shutdown
# switchport vlan-mapping 400-402,404,406,408,410,412,420,422,430-431 dot1q-tunnel 2436
#!

  - name: Overwrite the vlan mapping configurations
    sonic_vlan_mapping:
      config:
        - name: 'Ethernet8'
          mapping:
            - vlan_ids: '392'
              mapped_id: 2755
              dot1q_tunnel: false
              inner_vlan: 590
        - name: 'Ethernet16'
          mapping:
            - vlan_ids: '300'
              mapped_id: 2567
              dot1q_tunnel: true
              priority: 3
        - name: Portchannel 2
          mapping:
            - vlan_ids: '345'
              mapped_id: 2999
              priority: 0
      state: overridden

# After State:
# ------------
#
#sonic# show running-configuration interface
#!
#interface Ethernet8
# mtu 9100
# speed 400000
# fec RS
# unreliable-los auto
# shutdown
# switchport vlan-mapping 392 inner 590 2755
#!
#interface Ethernet16
# mtu 9100
# speed 400000
# fec RS
# unreliable-los auto
# shutdown
# switchport vlan-mapping 300 dot1q-tunnel 2567 priority 3
#!
#interface PortChannel 2
# switchport vlan-mapping 345 2999 priority 0
# no shutdown


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible.module_utils.network.sonic.argspec.vlan_mapping.vlan_mapping import Vlan_mappingArgs
from ansible.module_utils.network.sonic.config.vlan_mapping.vlan_mapping import Vlan_mapping


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=Vlan_mappingArgs.argument_spec,
                           supports_check_mode=True)

    result = Vlan_mapping(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
